### ISSUE TITLE
[New Upstream Release] 

### ISSUE THREAD

**Issue by OdinVex** [MeCJay12/lsi-storage-authority#2]
I believe there may be a new version, https://docs.broadcom.com/docs-and-downloads/raid-controllers/raid-controllers-common-files/007.020.016.000_LSA_Linux_x64.zip

**Comment by MeCJay12** [comment]
Done. Took some extra time because I found a bug in my entrypoint along the way. New version is on tag :ubuntu_007.020.016.000 or :dev. I'll move it to latest next week.

**Comment by MeCJay12** [comment]
Oh, yeah I use mwader/postfix-relay and it works well.

**Comment by MeCJay12** [comment]
Oof awkward. Typo corrected and bug resolved. Try it again. When a new container was made, the config file wasn't being created causing the service to boot loop.

For the upgrade still showing the old version of LSA, that sounds like you're mounting the whole /opt/lsi/LSIStorageAuthority/ directory instead of just /opt/lsi/LSIStorageAuthority/conf/. The service will not update files so if you mount the old binary it will boot the old binary.

**Comment by MeCJay12** [comment]
Ack. Updates pushed to the ubuntu_008.011.010.000 and dev tags. I usually give it a week to settle before pushing to latest. This will be a fun one. They changed the config format so you need to rebuild the config.

**Comment by MeCJay12** [comment]
I'm adding it to the comments in the Dockerfile so I remember but, at least this time (the process seems to change every time), going to https://docs.broadcom.com/docs/1232744305 automatically downloads the latest version then I can use my browser download history to get the direct link.

My typos!

**Comment by MeCJay12** [comment]
I think that the direct download link is updated on the backend auto-downloading page. So this link wouldn't change but the link it starts the download from would be continually updated. At least, that's the hope.

**Comment by MeCJay12** [comment]
I believe it is a single link and it automatically (redirects/rewrites) serves the latest.
It'll be hard to automatically build the container though because they seem to change the folder structure in the zip each time.
